# Generated by Django 2.1.7 on 2019-03-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20190323_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateblock',
            name='task4',
        ),
        migrations.RemoveField(
            model_name='dateblock',
            name='task5',
        ),
    ]
