# Generated by Django 2.1.7 on 2019-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20190324_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateinstance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
