# Generated by Django 2.1.7 on 2019-03-24 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20190324_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateinstance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
